# Generated by Django 5.0.7 on 2024-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=40)),
                ('event_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('calorie_per_dollar', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date_of_event', models.DateField()),
                ('time_of_event', models.TimeField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
